<a href="https://colab.research.google.com/github/5556mani/AI-Engineering/blob/main/PyTorch/3_Training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler as ss
from sklearn.preprocessing import LabelEncoder as le
from sklearn.model_selection import train_test_split as tts

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [ ]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
X_train , X_test , Y_train , Y_test = tts(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [ ]:
ss=ss()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [ ]:
le=le()
Y_train= le.fit_transform(Y_train)
Y_test=le.transform(Y_test)

In [ ]:
Y_test

tensor([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [ ]:
X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
Y_train=torch.from_numpy(Y_train)
Y_test=torch.from_numpy(Y_test)

# Define the Model using class


1.   def Class
2.   def init
3.   def forward_pass
4.   def loss function

In [ ]:
class Model():

  def __init__(self,X):
    self.weights=torch.rand((X.shape[1],1),dtype=torch.float64,requires_grad=True)
    self.bias=torch.tensor([1],dtype=torch.float64,requires_grad=True)

  def forward_pass(self,X):
    X=torch.matmul(X,self.weights)
    X=X+self.bias
    return X

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(Y_train * torch.log(y_pred) + (1 - Y_train) * torch.log(1 - y_pred)).mean()
    return loss

# Input Parameters

In [ ]:
learning_rate=0.1
epoch=50

# Training Pipeline

In [ ]:
model=Model(X_train)

print(model.weights.shape)
print(X_train.shape)

for epoch in range(epoch):
  Y_pred=model.forward_pass(X_train)

  loss=model.loss_function(Y_pred,Y_train)

  loss.backward()

  with torch.no_grad():
    model.weights-=model.weights.grad * learning_rate
    model.bias-=model.bias.grad * learning_rate

  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"epoch: {epoch}  loss: {loss}")

torch.Size([30, 1])
torch.Size([455, 30])
epoch: 0  loss: 7.459780435422582
epoch: 1  loss: 7.434105795670716
epoch: 2  loss: 7.430547225022992
epoch: 3  loss: 7.429978921260739
epoch: 4  loss: 7.429609815778464
epoch: 5  loss: 7.429342267722407
epoch: 6  loss: 7.42913389802183
epoch: 7  loss: 7.428963164447558
epoch: 8  loss: 7.4288181144981795
epoch: 9  loss: 7.428691685769529
epoch: 10  loss: 7.4285794660260445
epoch: 11  loss: 7.428478545438399
epoch: 12  loss: 7.42838690227501
epoch: 13  loss: 7.428303063121336
epoch: 14  loss: 7.428225908878546
epoch: 15  loss: 7.428154560097478
epoch: 16  loss: 7.428088306577653
epoch: 17  loss: 7.428026562369575
epoch: 18  loss: 7.427968835828162
epoch: 19  loss: 7.427914708899315
epoch: 20  loss: 7.427863822279491
epoch: 21  loss: 7.427815864447962
epoch: 22  loss: 7.427770563341965
epoch: 23  loss: 7.427727679893486
epoch: 24  loss: 7.427687002915019
epoch: 25  loss: 7.42764834498739
epoch: 26  loss: 7.427611539108239
epoch: 27  loss: 7.427576435928604
epoch: 28  loss: 7.4275429014516785
epoch: 29  loss: 7.4275108150997005
epoch: 30  loss: 7.427480068077685
epoch: 31  loss: 7.4274505619790805
epoch: 32  loss: 7.4274222075903165
epoch: 33  loss: 7.427394923860409
epoch: 34  loss: 7.42736863700837
epoch: 35  loss: 7.427343279746609
epoch: 36  loss: 7.427318790602466
epoch: 37  loss: 7.427295113323244
epoch: 38  loss: 7.4272721963527095
epoch: 39  loss: 7.427249992368947
epoch: 40  loss: 7.4272284578752386
epoch: 41  loss: 7.427207552836839
epoch: 42  loss: 7.427187240357689
epoch: 43  loss: 7.427167486392004
epoch: 44  loss: 7.427148259486363
epoch: 45  loss: 7.427129530548628
epoch: 46  loss: 7.427111272640453
epoch: 47  loss: 7.427093460790652
epoch: 48  loss: 7.427076071827026